use crate::common::json_io::parse_work_units_array;
use crate::common::walk::{walk_source_files, SOURCE_TREE_EXCLUDES};
use crate::common::Stack;
use anyhow::{anyhow, Context};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(clap::Args, Debug)]
pub struct Args {
    #[arg(long)]
    pub repro_path: PathBuf,
    #[arg(long)]
    pub target_file: String,
    #[arg(long)]
    pub target_function: String,
    #[arg(long, value_enum)]
    pub stack: Stack,
    #[arg(long)]
    pub repo_root: PathBuf,
    #[arg(long)]
    pub work_units_file: PathBuf,
    #[arg(long)]
    pub output_test_file: Option<PathBuf>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ReproducerResult {
    pub test_file: PathBuf,
    pub test_name: String,
    pub artifact_sha256: String,
    pub input_bytes: usize,
    pub work_unit_appended: bool,
}

/// Formats a byte slice as a Rust `&[u8]` literal, line-wrapping every 12 entries.
pub fn format_rust_byte_literal(bytes: &[u8]) -> String {
    let mut out = String::from("&[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if i > 0 && i % 12 == 0 {
            out.push('\n');
            out.push_str("    ");
        }
        let _ = write!(out, "0x{:02x}", b);
    }
    out.push(']');
    out
}

/// Formats a byte slice as a C# `new byte[] { ... }` literal, line-wrapping every 12 entries.
pub fn format_csharp_byte_literal(bytes: &[u8]) -> String {
    let mut out = String::from("new byte[] { ");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if i > 0 && i % 12 == 0 {
            out.push('\n');
            out.push_str("    ");
        }
        let _ = write!(out, "0x{:02x}", b);
    }
    out.push_str(" }");
    out
}

/// Returns lowercase hex SHA-256 of `bytes` and the 12-char short prefix.
pub fn sha256_with_short(bytes: &[u8]) -> (String, String) {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let hex = format!("{:x}", hasher.finalize());
    let short = hex.chars().take(12).collect();
    (hex, short)
}

fn find_enclosing_cargo_toml(start: &Path) -> Option<PathBuf> {
    let mut cur = if start.is_file() {
        start.parent()?.to_path_buf()
    } else {
        start.to_path_buf()
    };
    loop {
        let candidate = cur.join("Cargo.toml");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !cur.pop() {
            return None;
        }
    }
}

fn extract_crate_name(cargo_toml: &Path) -> Option<String> {
    let content = fs::read_to_string(cargo_toml).ok()?;
    let mut in_package = false;
    for line in content.lines() {
        let trimmed = line.trim();
        // Section header: [package], [lib], [[bin]], [dependencies.foo], etc.
        if let Some(inside) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            // Handle array-of-tables [[bin]] by stripping the inner brackets.
            let inside = inside.strip_prefix('[').unwrap_or(inside);
            let inside = inside.strip_suffix(']').unwrap_or(inside);
            in_package = inside == "package";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("name") {
            let rest = rest.trim_start_matches([' ', '\t', '=']).trim();
            if let Some(name) = rest.strip_prefix('"') {
                if let Some(end) = name.find('"') {
                    return Some(name[..end].to_string());
                }
            }
        }
    }
    None
}

pub fn generate_rust_reproducer(
    bytes: &[u8],
    target_function: &str,
    crate_name: Option<&str>,
    artifact_label: &str,
) -> (String, String) {
    let (_, short) = sha256_with_short(bytes);
    let test_name = format!("fuzz_repro_{}", short);
    let byte_lit = format_rust_byte_literal(bytes);
    let timestamp = Utc::now().format("%Y-%m-%d").to_string();
    // For paths like `Parser::parse_header` we cannot emit `use crate::Parser::parse_header;`
    // (Rust does not permit importing a method via `use`). Always import only up to the
    // second-to-last segment — that works whether the final segment is a method on a type
    // (`Parser::parse_header` -> `use crate::Parser;`) or a function in a module
    // (`parser::parse_header` -> `use crate::parser;`).
    let use_stmt = match crate_name {
        Some(name) => match target_function.rsplit_once("::") {
            Some((prefix, _last)) => format!("use {}::{};", name, prefix),
            None => format!("use {}::{};", name, target_function),
        },
        None => format!("// adjust this `use` to import {}", target_function),
    };
    let content = format!(
        "// AUTOGENERATED by straightjacket plugin (fuzz reproducer).\n\
         // Date: {timestamp}. Source artifact: {artifact_label}.\n\
         \n\
         {use_stmt}\n\
         \n\
         #[test]\n\
         fn {test_name}() {{\n\
         \x20   let input: &[u8] = {byte_lit};\n\
         \x20   // The target previously panicked on this input (fuzz-discovered {timestamp}).\n\
         \x20   // The contract is: it must not panic; it may return Err.\n\
         \x20   let _ = {target_function}(input);\n\
         }}\n"
    );
    (test_name, content)
}

pub fn generate_csharp_reproducer(
    bytes: &[u8],
    target_function: &str,
    artifact_label: &str,
) -> anyhow::Result<(String, String)> {
    let parts: Vec<&str> = target_function.split('.').collect();
    if parts.len() < 2 {
        return Err(anyhow!(
            "C# target function must be qualified like 'Type.Method'; got: {}",
            target_function
        ));
    }
    let (_, short) = sha256_with_short(bytes);
    let test_name = format!("FuzzRepro_{}", short);
    let byte_lit = format_csharp_byte_literal(bytes);
    let timestamp = Utc::now().format("%Y-%m-%d").to_string();
    let type_name = parts[..parts.len() - 1].join(".");
    let method_name = parts[parts.len() - 1];

    let content = format!(
        "// AUTOGENERATED by straightjacket plugin (fuzz reproducer).\n\
         // Date: {timestamp}. Source artifact: {artifact_label}.\n\
         \n\
         using Xunit;\n\
         \n\
         namespace FuzzRegressions;\n\
         \n\
         public class FuzzRegressions\n\
         {{\n\
         \x20   [Fact]\n\
         \x20   public void {test_name}()\n\
         \x20   {{\n\
         \x20       var input = {byte_lit};\n\
         \x20       // The target previously threw on this input (fuzz-discovered {timestamp}).\n\
         \x20       var exception = Record.Exception(() => {type_name}.{method_name}(input));\n\
         \x20       Assert.Null(exception);\n\
         \x20   }}\n\
         }}\n"
    );
    Ok((test_name, content))
}

fn append_work_unit(
    work_units_file: &Path,
    target_file: &str,
    target_function: &str,
    short_hash: &str,
    input_len: usize,
    output_file_path: &Path,
    test_name: &str,
) -> anyhow::Result<()> {
    let timestamp = Utc::now().format("%Y-%m-%d").to_string();
    let new_unit = serde_json::json!({
        "id": uuid::Uuid::new_v4().to_string(),
        "target_file": target_file,
        "target_symbol": target_function,
        "kind": "unit",
        "intended_behavior": format!(
            "Function {target_function} must not panic/throw on input X (fuzz-discovered {timestamp}, sha256 prefix {short_hash})"
        ),
        "preconditions": "",
        "inputs": format!("byte sequence (sha256 {short_hash}, {input_len} bytes)"),
        "expected": "no panic / no unhandled exception",
        "fuzzable": false,
        "output_file_path": output_file_path.to_string_lossy(),
        "output_test_name": test_name,
        "status": "written",
        "round": -1,
        "source_of_unit": "fuzz_runner",
    });

    let mut existing: Vec<serde_json::Value> = if work_units_file.exists() {
        let text = fs::read_to_string(work_units_file)
            .with_context(|| format!("read {}", work_units_file.display()))?;
        let parsed: serde_json::Value = serde_json::from_str(&text).with_context(|| {
            format!(
                "parse existing work-units file {} (refusing to clobber malformed JSON)",
                work_units_file.display()
            )
        })?;
        // Strict-accept: refuse to silently clobber an unrecognized work-units file shape.
        match parse_work_units_array(&parsed) {
            Some(slice) => slice.to_vec(),
            None => {
                return Err(anyhow!(
                    "work-units file must be a JSON array or an object with a `work_units` array: {}",
                    work_units_file.display()
                ))
            }
        }
    } else {
        Vec::new()
    };
    existing.push(new_unit);

    if let Some(parent) = work_units_file.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("create dir {}", parent.display()))?;
        }
    }
    let serialized = serde_json::to_string_pretty(&existing)?;
    fs::write(work_units_file, serialized + "\n")
        .with_context(|| format!("write {}", work_units_file.display()))?;
    Ok(())
}

pub fn run(args: Args) -> anyhow::Result<()> {
    let bytes = fs::read(&args.repro_path)
        .with_context(|| format!("read reproducer artifact {}", args.repro_path.display()))?;
    let (full_sha, short_hash) = sha256_with_short(&bytes);

    let output_file = if let Some(p) = args.output_test_file.clone() {
        p
    } else {
        match args.stack {
            Stack::Rust => {
                let target_abs = args.repo_root.join(&args.target_file);
                let cargo = find_enclosing_cargo_toml(&target_abs).ok_or_else(|| {
                    anyhow!("could not locate enclosing Cargo.toml for {}", args.target_file)
                })?;
                let crate_root = cargo.parent().unwrap().to_path_buf();
                let tests_dir = crate_root.join("tests");
                fs::create_dir_all(&tests_dir)
                    .with_context(|| format!("create {}", tests_dir.display()))?;
                tests_dir.join("fuzz_regressions.rs")
            }
            Stack::Csharp => {
                // Find first *.Tests / *.Test project under repo_root and place under its
                // FuzzRegressions/ subdir.
                let csproj =
                    walk_source_files(&args.repo_root, SOURCE_TREE_EXCLUDES, &["csproj"])?
                        .into_iter()
                        .find(|p| {
                            p.file_stem()
                                .and_then(|s| s.to_str())
                                .map(|s| {
                                    s.ends_with(".Tests")
                                        || s.ends_with(".Test")
                                        || s.ends_with(".UnitTests")
                                        || s.ends_with(".IntegrationTests")
                                })
                                .unwrap_or(false)
                        })
                        .ok_or_else(|| anyhow!("no *.Tests project found under {}", args.repo_root.display()))?;
                let tests_dir = csproj.parent().unwrap().join("FuzzRegressions");
                fs::create_dir_all(&tests_dir)
                    .with_context(|| format!("create {}", tests_dir.display()))?;
                tests_dir.join("FuzzRegressions.cs")
            }
            _ => return Err(anyhow!("stack must be rust or csharp; got {:?}", args.stack)),
        }
    };

    let test_name: String = match args.stack {
        Stack::Rust => {
            let cargo = find_enclosing_cargo_toml(&output_file);
            let crate_name = cargo.as_deref().and_then(extract_crate_name);
            let (test_name, body) = generate_rust_reproducer(
                &bytes,
                &args.target_function,
                crate_name.as_deref(),
                &args.repro_path.to_string_lossy(),
            );
            // Append vs create — preserve existing tests if file exists, just append the new test fn.
            if output_file.is_file() {
                let existing = fs::read_to_string(&output_file).unwrap_or_default();
                // If file lacks our header, append it once.
                let new_content = if existing.contains("AUTOGENERATED by straightjacket plugin") {
                    // Already has header; append body only
                    let only_body = body
                        .split_once("\n#[test]")
                        .map(|(_, after)| format!("\n#[test]{after}"))
                        .unwrap_or(body);
                    format!("{existing}{only_body}")
                } else {
                    format!("{existing}\n{body}")
                };
                fs::write(&output_file, new_content)?;
            } else {
                fs::write(&output_file, body)?;
            }
            test_name
        }
        Stack::Csharp => {
            let (test_name, content) = generate_csharp_reproducer(
                &bytes,
                &args.target_function,
                &args.repro_path.to_string_lossy(),
            )?;
            if output_file.is_file() {
                let existing = fs::read_to_string(&output_file).unwrap_or_default();
                let last_brace = existing.rfind('}').ok_or_else(|| {
                    anyhow!("could not locate class closing brace in {}", output_file.display())
                })?;
                let inserted = {
                    let inner_body = content
                        .split_once("    [Fact]")
                        .map(|(_, rest)| format!("    [Fact]{rest}"))
                        .unwrap_or(content.clone());
                    // Strip the trailing class brace from inserted snippet
                    let inner_body = inner_body
                        .rsplit_once('}')
                        .map(|(before, _)| before.to_string())
                        .unwrap_or(inner_body);
                    inner_body
                };
                let new_content = format!(
                    "{}{}\n}}{}",
                    &existing[..last_brace],
                    inserted,
                    &existing[last_brace + 1..]
                );
                fs::write(&output_file, new_content)?;
            } else {
                fs::write(&output_file, content)?;
            }
            test_name
        }
        _ => unreachable!(),
    };

    append_work_unit(
        &args.work_units_file,
        &args.target_file,
        &args.target_function,
        &short_hash,
        bytes.len(),
        &output_file,
        &test_name,
    )?;

    let result = ReproducerResult {
        test_file: output_file,
        test_name,
        artifact_sha256: full_sha,
        input_bytes: bytes.len(),
        work_unit_appended: true,
    };
    println!("{}", serde_json::to_string_pretty(&result)?);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn rust_byte_literal_for_empty_slice() {
        assert_eq!(format_rust_byte_literal(&[]), "&[]");
    }

    #[test]
    fn rust_byte_literal_uses_hex_zero_padded_lowercase() {
        assert_eq!(format_rust_byte_literal(&[0x01, 0xab, 0xff]), "&[0x01, 0xab, 0xff]");
    }

    #[test]
    fn rust_byte_literal_wraps_every_12_entries() {
        let bytes: Vec<u8> = (0..15u8).collect();
        let lit = format_rust_byte_literal(&bytes);
        assert!(lit.contains('\n'), "expected newline in 15-byte literal: {}", lit);
        // Should still be parseable: balanced brackets, correct count of "0x" markers
        assert_eq!(lit.matches("0x").count(), 15);
    }

    #[test]
    fn csharp_byte_literal_for_two_bytes() {
        assert_eq!(
            format_csharp_byte_literal(&[0x10, 0x20]),
            "new byte[] { 0x10, 0x20 }"
        );
    }

    #[test]
    fn sha256_short_hash_is_12_lowercase_hex_chars() {
        let (full, short) = sha256_with_short(b"hello");
        assert_eq!(full.len(), 64);
        assert_eq!(short.len(), 12);
        assert!(short.chars().all(|c| c.is_ascii_hexdigit()));
        // Known SHA-256 of "hello"
        assert!(full.starts_with("2cf24dba"));
    }

    #[test]
    fn enclosing_cargo_toml_finds_parent() {
        let td = TempDir::new().unwrap();
        let crate_root = td.path().join("mycrate");
        fs::create_dir_all(crate_root.join("src")).unwrap();
        fs::write(crate_root.join("Cargo.toml"), "[package]\nname = \"mycrate\"\n").unwrap();
        let src_file = crate_root.join("src").join("lib.rs");
        fs::write(&src_file, "").unwrap();
        let found = find_enclosing_cargo_toml(&src_file).unwrap();
        assert_eq!(found, crate_root.join("Cargo.toml"));
    }

    #[test]
    fn enclosing_cargo_toml_returns_none_when_no_manifest() {
        let td = TempDir::new().unwrap();
        let nested = td.path().join("a").join("b");
        fs::create_dir_all(&nested).unwrap();
        let result = find_enclosing_cargo_toml(&nested);
        assert!(result.is_none());
    }

    #[test]
    fn extract_crate_name_from_cargo_toml() {
        let td = TempDir::new().unwrap();
        let cargo = td.path().join("Cargo.toml");
        fs::write(&cargo, "[package]\nname = \"foo-bar\"\nversion = \"1.0.0\"\n").unwrap();
        assert_eq!(extract_crate_name(&cargo), Some("foo-bar".to_string()));
    }

    #[test]
    fn rust_reproducer_includes_test_name_and_call_site() {
        let bytes = b"abc";
        let (test_name, content) =
            generate_rust_reproducer(bytes, "parser::parse_header", Some("mycrate"), "artifact");
        assert!(test_name.starts_with("fuzz_repro_"));
        assert!(content.contains("#[test]"));
        assert!(content.contains(&test_name));
        assert!(content.contains("parser::parse_header(input)"));
        // Imports the parent module/type only — never the method.
        assert!(content.contains("use mycrate::parser;"));
        assert!(!content.contains("use mycrate::parser::parse_header;"));
    }

    #[test]
    fn csharp_reproducer_includes_type_method_split() {
        let (test_name, content) =
            generate_csharp_reproducer(b"abc", "Parser.ParseHeader", "artifact").unwrap();
        assert!(test_name.starts_with("FuzzRepro_"));
        assert!(content.contains("[Fact]"));
        assert!(content.contains("Parser.ParseHeader(input)"));
    }

    #[test]
    fn csharp_reproducer_rejects_unqualified_target_function() {
        let r = generate_csharp_reproducer(b"x", "BareFunction", "artifact");
        assert!(r.is_err());
    }

    #[test]
    fn append_work_unit_creates_new_file_with_array() {
        let td = TempDir::new().unwrap();
        let wu_path = td.path().join("work-units.json");
        let test_file = td.path().join("fuzz_regressions.rs");
        append_work_unit(
            &wu_path,
            "src/parser.rs",
            "parser::parse_header",
            "abc123",
            42,
            &test_file,
            "fuzz_repro_abc123",
        )
        .unwrap();
        let content = fs::read_to_string(&wu_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 1);
        assert_eq!(arr[0]["target_file"], "src/parser.rs");
        assert_eq!(arr[0]["round"], -1);
        assert_eq!(arr[0]["source_of_unit"], "fuzz_runner");
    }

    #[test]
    fn append_work_unit_appends_to_existing_array() {
        let td = TempDir::new().unwrap();
        let wu_path = td.path().join("work-units.json");
        fs::write(&wu_path, "[{\"id\":\"old\",\"target_file\":\"x\"}]\n").unwrap();
        append_work_unit(
            &wu_path,
            "src/parser.rs",
            "parser::parse_header",
            "def456",
            10,
            &td.path().join("t.rs"),
            "fuzz_repro_def456",
        )
        .unwrap();
        let content = fs::read_to_string(&wu_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 2);
        assert_eq!(arr[0]["id"], "old");
    }

    // --- new tests added by unit-test-author ---

    #[test]
    fn test_extract_crate_name_ignores_name_keys_outside_package_section() {
        // A Cargo.toml where a `name` key appears in [lib] before [package].
        // The function must return the value from [package], not the first textual match.
        let td = TempDir::new().unwrap();
        let cargo = td.path().join("Cargo.toml");
        fs::write(
            &cargo,
            "[lib]\nname = \"wrong-name\"\n\n[package]\nname = \"correct-name\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        assert_eq!(extract_crate_name(&cargo), Some("correct-name".to_string()));
    }

    #[test]
    fn test_generate_rust_reproducer_emits_valid_use_for_type_method_paths() {
        // target_function contains `::` with a Type-style first segment (e.g. `Parser::parse_header`).
        // Emitting `use mycrate::Parser::parse_header;` is invalid Rust.
        // The function must NOT produce that exact invalid form.
        let bytes = b"input";
        let (_test_name, content) =
            generate_rust_reproducer(bytes, "Parser::parse_header", Some("mycrate"), "artifact");
        assert!(
            !content.contains("use mycrate::Parser::parse_header;"),
            "emitted invalid `use` form `use mycrate::Parser::parse_header;`:\n{content}"
        );
    }

    #[test]
    fn test_rust_byte_literal_wraps_exactly_at_thirteenth_byte_not_twelfth() {
        // 12 bytes: all fit on one row — zero embedded newlines.
        let twelve: Vec<u8> = (0u8..12).collect();
        let lit12 = format_rust_byte_literal(&twelve);
        assert_eq!(
            lit12.matches('\n').count(),
            0,
            "12-byte literal should have 0 newlines, got: {lit12}"
        );

        // 13 bytes: the 13th entry (index 12) triggers the wrap — exactly one newline.
        let thirteen: Vec<u8> = (0u8..13).collect();
        let lit13 = format_rust_byte_literal(&thirteen);
        assert_eq!(
            lit13.matches('\n').count(),
            1,
            "13-byte literal should have exactly 1 newline, got: {lit13}"
        );
    }

    #[test]
    fn test_append_work_unit_does_not_silently_clobber_malformed_existing_file() {
        // When the existing work-units.json contains malformed JSON, append_work_unit must
        // either (a) return an Err, OR (b) leave the original file content intact.
        // What it must NOT do: return Ok and silently overwrite with a fresh single-element array.
        let td = TempDir::new().unwrap();
        let wu_path = td.path().join("work-units.json");
        let malformed = "[{not valid json sentinel_unique_string";
        fs::write(&wu_path, malformed).unwrap();

        let result = append_work_unit(
            &wu_path,
            "src/parser.rs",
            "parser::parse_header",
            "aaa111",
            7,
            &td.path().join("t.rs"),
            "fuzz_repro_aaa111",
        );

        let after = fs::read_to_string(&wu_path).unwrap_or_default();
        // Silent clobber: returned Ok AND the file is now a clean single-element valid array
        // AND the original sentinel is gone.
        let silently_clobbered = result.is_ok()
            && serde_json::from_str::<Vec<serde_json::Value>>(&after)
                .map(|a| a.len() == 1)
                .unwrap_or(false)
            && !after.contains("sentinel_unique_string");
        assert!(
            !silently_clobbered,
            "silent clobber detected: result={result:?}, file after=\n{after}"
        );
    }

    #[test]
    fn test_sha256_with_short_for_empty_input_uses_known_value() {
        // Known SHA-256 of the empty byte sequence.
        let (full, short) = sha256_with_short(&[]);
        assert_eq!(
            full,
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(short, "e3b0c44298fc");
    }

    #[test]
    fn test_generate_csharp_reproducer_preserves_multi_segment_namespace_path() {
        // target_function has more than two segments (e.g., `MyApp.Parsers.Header.Parse`).
        // All-but-last segments must form the type/namespace path; the call site must read
        // `MyApp.Parsers.Header.Parse(input)` (dots preserved, not just the last two segments).
        let (_test_name, content) =
            generate_csharp_reproducer(b"data", "MyApp.Parsers.Header.Parse", "artifact").unwrap();
        assert!(
            content.contains("MyApp.Parsers.Header.Parse(input)"),
            "multi-segment call site not found in:\n{content}"
        );
    }

    /// Lock the wrapper-object acceptance: when work-units.json already exists in the
    /// orchestrator's `{"work_units": [...], "scope_summary": ...}` shape, append_work_unit
    /// must extract the inner array, push the new fuzz-discovered unit, and not drop
    /// existing entries. The pre-existing entry must survive the append.
    #[test]
    fn test_append_work_unit_accepts_orchestrator_wrapper_object_shape() {
        let td = TempDir::new().unwrap();
        let wu_path = td.path().join("work-units.json");

        let existing_wrapper = serde_json::json!({
            "work_units": [
                {
                    "id": "preexisting-unit-aaaa",
                    "target_file": "src/old.rs",
                    "target_symbol": "old::sym",
                    "status": "written"
                }
            ],
            "scope_summary": "wrapper-level metadata from coverage-reviewer"
        });
        fs::write(
            &wu_path,
            serde_json::to_string_pretty(&existing_wrapper).unwrap(),
        )
        .unwrap();

        let result = append_work_unit(
            &wu_path,
            "src/parser.rs",
            "parser::parse_header",
            "bbb222",
            42,
            &td.path().join("t.rs"),
            "fuzz_repro_bbb222",
        );
        assert!(
            result.is_ok(),
            "append_work_unit must accept wrapper-shape work-units.json; got: {result:?}"
        );

        // Read back. After the fix, the file is written as a bare array (the wrapper's
        // top-level scope_summary etc. are intentionally not preserved on append; the
        // critical invariant is that the inner array's contents survive).
        let after_text = fs::read_to_string(&wu_path).unwrap();
        let after: serde_json::Value = serde_json::from_str(&after_text).unwrap();
        let after_arr = after.as_array().expect(
            "after append, file should be a bare array (or extract via parse_work_units_array)",
        );
        assert_eq!(
            after_arr.len(),
            2,
            "wrapper inner array's 1 entry + 1 appended = 2; got: {after_arr:?}"
        );
        let ids: Vec<&str> = after_arr
            .iter()
            .filter_map(|v| v.get("id").and_then(|s| s.as_str()))
            .collect();
        assert!(
            ids.contains(&"preexisting-unit-aaaa"),
            "pre-existing unit from the wrapper's inner array must survive the append; got ids: {ids:?}"
        );
    }
}
